created a reusable component to embed facebook and twitter in websites
scorelab/Webiu pull request #34
Opened 2021-02-12 10:12 UTC by Grumpyyash

This PR fixes #32 
Created a reusable component to embed Facebook and Twitter mark-ups in the website where the profile name has to be passed as a prop to the component and it would render the desired result. This is also open to being extended to include LinkedIn and youtube mark-ups as well. 
It uses Facebook and Twitter APIs to render data.
![twitter-embed](https://user-images.githubusercontent.com/62200066/107755501-e57a4300-6d48-11eb-9aed-c0f2f221ede0.png)

2021-02-12 10:13 UTC, Grumpyyash commented
Could you please review the PR? @wdevon99  @charithccmc

2021-02-21 05:29 UTC, wdevon99 requested changes
Styling should improve and style should be customizable via props and also  these links are not API links so the naming of the constants are incorrect :)

2021-02-21 07:27 UTC, Grumpyyash commented
@wdevon99 I have updated the names of constants and have customized styles and header text through props. Please review it now.

![facebook-twitter](https://user-images.githubusercontent.com/62200066/108618445-4e964080-7444-11eb-8039-388379fc1bfc.png)

2021-06-08 15:46 UTC, wdevon99 requested changes
You can just make this a resable IFRAME component and dont need to restirct to only socail media sites

2021-07-18 06:43 UTC, closed without merging